class bike {
bike()
{
	System.out.print("Bike is Created");
}
	public static void main(String[] args) {
		bike b =new bike();// te value of local variable is not used 
	}

}
//output is generated by default constructor.
//default constructor is used to give a default value to a object.
//that can b 0,null . it depend what we are using.